# Generated by Django 5.2.7 on 2025-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0003_customcolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiteboard",
            name="background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
