# Generated by Django 5.2.7 on 2025-11-05 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whiteboard", "0004_whiteboard_background_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteboardViewSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zoom", models.FloatField(default=1.0)),
                ("pan_x", models.FloatField(default=0.0)),
                ("pan_y", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_view_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_settings",
                        to="whiteboard.whiteboard",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "whiteboard")},
            },
        ),
    ]
