apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: stickytux-frontend
  labels:
    app: stickytux
    component: frontend
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: stickytux-backend
  labels:
    app: stickytux
    component: backend
spec:
  lookupPolicy:
    local: false