apiVersion: v1
kind: Secret
metadata:
  name: stickytux-secrets
  labels:
    app: stickytux
type: Opaque
stringData:
  # Replace these with actual values
  database-url: "sqlite:////app/data/db.sqlite3"
  secret-key: "your-secret-key-here"
  redis-url: "redis://localhost:6379/0"